import'@/app/globals.css';
import Navbar from "./navbar";
export const metadata = {
  title: {
    default: "portfolio",
    template: "",
    absolute: "",
  },
  description: "generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="eng">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
