export const metadata = {
  title: "Contact | Portfolio",
  description: "Contact Areeb - Frontend Developer Portfolio",
};

export default function Contact() {
  return (
    <div className="max-w-5xl mx-auto p-6">
      <div className="flex flex-col md:flex-row gap-8">
        {/* Contact Form */}
        <form className="flex-1 bg-gray-100 p-6 rounded-lg shadow space-y-4">
          <h2 className="text-2xl font-bold mb-4">Send a message to me</h2>

          <div className="flex flex-col">
            <label htmlFor="name" className="text-sm mb-1">Name</label>
            <input
              id="name"
              type="text"
              className="p-3 rounded border border-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex flex-col">
            <label htmlFor="email" className="text-sm mb-1">Email</label>
            <input
              id="email"
              type="email"
              className="p-3 rounded border border-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex flex-col">
            <label htmlFor="message" className="text-sm mb-1">Message</label>
            <textarea
              id="message"
              rows={5}
              className="p-3 rounded border border-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
            ></textarea>
          </div>

          <button className="bg-blue-600 text-white py-3 px-6 rounded hover:bg-blue-700 transition">
            Send Message
          </button>
        </form>

        {/* Contact Info */}
        <div className="flex-1 bg-gray-100 p-6 rounded-lg shadow space-y-3">
          <h2 className="text-2xl font-bold mb-2">Contact Information</h2>
          <p className="font-semibold">Email:</p>
          <a href="mailto:officialareebsafdar@gmail.com" className="text-blue-600 hover:underline text-sm">
            officialareebsafdar@gmail.com
          </a>
          <br/>
          <a href="https://www.linkedin.com/in/areeb-safdar-a42649376" className="text-blue-600 hover:underline text-sm">
            www.linkedin.com/in/areeb-safdar-a42649376
          </a>
          <a href="https://github.com/AreebSafdar" className="text-blue-600 hover:underline text-sm">
            GitHub: github.com/AreebSafdar
          </a>
          <p className="font-semibold mt-2">Location:</p>
          <p className="text-sm">Rahim Yar Khan, Pakistan</p>

          <p className="font-semibold mt-2">Social:</p>
          <p className="text-sm">TikTok, Instagram, LinkedIn</p>
        </div>
      </div>
    </div>
  );
}


// export const metadata = {
//   title: {
//     default: "contect/piclume",
//     template:"",
//    absolute:"",
//   },
//   description:"generated by Next.js",
// };
// export default function piclum(){
//   return(
//     <div style={{
//             display:" grid",
//             gap: "1%",
//             gridTemplateColumns: "repeat(2, auto)",
//              padding: "0 90px",
//                     width: "24.99999%",
//     }}>
//     <div style={{
//         fontFamily:"Arial, Helvetica, sans-serif",
//         padding: "0 130px",
//        width: "44.99999%",
//      }}>
//         <h3>Send message to me</h3>
//         <label style={{
//         fontSize:"13px",
//       }}>Name</label><br/>
//         <input type="text" style={{
//              borderRadius:"9px" ,
//              border:"1px solid black",
//              padding: "9px 50px",
//              textAlign:"left",
//             marginTop:"10px",
//     }}></input><br/>
//         <label style={{
//         fontSize:"13px",
//       }}>Email</label><br/>
//         <input type="text" style={{
//              borderRadius:"9px" ,
//              padding: "9px 50px",
//              border:"1px solid black",
//              marginTop:"10px",
//             }}>
//         </input><br/>
//         <label style={{
//         fontSize:"13px",
//       }}>Message</label><br/>
//         <textarea name="message" style={{
//              borderRadius:"9px" ,
//              border:"1px solid black",
//              padding: "9px 50px",
//              marginTop:"10px",
//     }}></textarea>
//     <button style={{
//              borderRadius:"9px" ,
//              border:"1px solid black",
//              padding: "10px 90px",
//              backgroundColor:"blue",
//              color:"white",
//              marginTop:"10px",
//     }}>SendMessage</button>
//         </div>
//  <div style={{
//         fontFamily:"Arial, Helvetica, sans-serif",
//                 width: "104.99999%",
//        }}>
//         <h3 style={{
//         }}>Contect..Information</h3>
//         <p>Email</p>
//         <a href="/" style={{
//            textDecoration: "none",
//                    fontSize:"13px",
//         }}>officalareebsafdar@gmail</a>
//          <p>Location</p>
//         <p  style={{
//         fontSize:"13px",
//       }}>Rahim yar Khan, Pakistan</p>
//         <p>Contact with me</p>
//         <p style={{
//         fontSize:"13px",
//       }}>TikTok, Instagram &#128514;&#128514;</p>
//     </div>
//         </div>
//         );}