export const metadata = {
  title: "Blog / Piclume",
  description: "Generated by Next.js",
};
export default function BlogCard() {
  return (
    <div className="flex flex-col items-center p-4">
      <article className="bg-white shadow-md rounded-lg p-6 w-full max-w-2xl">
        <p className="text-gray-500 text-sm mb-2">March 20, 2024 · 5 min read</p>
        <h2 className="text-2xl font-bold mb-3">Blog Post Title</h2>
        <p className="text-gray-700 mb-4">
          A brief excerpt from your blog post that gives readers preview of what to expect....
        </p>
        <div className="flex gap-2 mb-4">
          <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">React</span>
          <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">Next.js</span>
        </div>
        <a
          href="/register"
          className="text-blue-600 hover:underline font-medium text-sm"
        >
          Read more →
        </a>
      </article>

      <footer className="flex items-center justify-center mt-6 gap-4">
        <button className="border border-black rounded px-4 py-2 hover:bg-gray-100">Previous</button>
        <span className="text-gray-600 text-sm">Page 1 of 1</span>
        <button className="border border-black rounded px-4 py-2 hover:bg-gray-100">Next</button>
      </footer>
    </div>
  );
}



// export const metadata = {
//   title: {
//     default: "Blog/piclume",
//     template:"",
//    absolute:"",
//   },
//   description:"generated by Next.js",
// };
// export default function piclum(){
//   return(
//    <div style={{
//     borderRadius:"8px" ,
//     padding: "3px 10px",
//     marginLeft:"30%",
//  }}>
// <div style={{
//     borderRadius:"8px" ,
//     backgroundColor:"#f1f1f1f1",
//         padding: "10px 18px",
//         width:"60%",
//     border:" outset",
//     fontFamily:"Arial, Helvetica, sans-serif",
//  }}>
// <p style={{
//     color:"gray",
//     fontSize:"13px",
//     fontFamily:"Arial, Helvetica, sans-serif",
//  }}>March 20,2024 . 5 min read</p>
// <h2 style={{
//     textAlign:"left",
//     fontFamily:"Arial, Helvetica, sans-serif",
//  }}>Blog Post Title</h2>
// <p style={{
//     color:"gray",
//     fontSize:"13px",
//     fontFamily:"Arial, Helvetica, sans-serif",
//  }}>A brief expecrt from your blog post that gives readers preview of what to expect....</p>
// <a style={{
//     backgroundColor:"gray",
//     borderRadius:"15px" ,
//         fontSize:"13px",
//     padding: "7px 20px",
//  }}>React</a><a style={{
//     backgroundColor:"gray",
//     borderRadius:"15px" ,
//         fontSize:"13px",
//     padding: "7px 20px",
//     marginLeft:"20px"
//  }}> Next.js</a>
//  <a href="http://localhost:3000/register" style={{
//     borderRadius:"15px" ,
//         fontSize:"13px",
//         color:"blue",
//         textDecoration:"none",
//     padding: "7px 20px",
//     marginLeft:"38%"
//  }}>Read more&#8594;</a>
//  <h1></h1>
// </div>
// <div style={{
//     marginTop:"20px",
//         marginLeft:"10%",
//         fontFamily:"Arial, Helvetica, sans-serif",
//  }}>
//     <button style={{
// border:"1px solid black",
// borderRadius:"7px" ,
// backgroundColor:"white",
//         fontSize:"13px",
//     padding: "7px 20px",
//     marginLeft:"20px"
//  }}>Previous</button>
//  <a style={{
// color:"gray",
//  fontSize:"14px",
//      marginLeft:"20px"
//  }}> Page 1 of 1 </a>
//  <button style={{
//     borderRadius:"7px" ,
//     border:"1px solid black",
//         fontSize:"13px",
//         backgroundColor:"white",

//     padding: "7px 30px",
//     marginLeft:"20px"
//  }}>Next</button>
// </div>
// </div>
//   )
// };