export const metadata = {
  title: "Blog / Piclume",
  description: "Generated by Next.js",
};
export default function BlogCard() {
  return (
    <div className="flex flex-col items-center p-4">
      <article className="bg-white shadow-md rounded-lg p-6 w-full max-w-2xl">
        <p className="text-gray-500 text-sm mb-2">March 20, 2024 · 5 min read</p>
        <h2 className="text-2xl font-bold mb-3">Blog Post Title</h2>
        <p className="text-gray-700 mb-4">
          A brief excerpt from your blog post that gives readers preview of what to expect....
        </p>
        <div className="flex gap-2 mb-4">
          <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">React</span>
          <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">Next.js</span>
        </div>
        <a
          href="/register"
          className="text-blue-600 hover:underline font-medium text-sm"
        >
          Read more →
        </a>
      </article>

      <footer className="flex items-center justify-center mt-6 gap-4">
        <button className="border border-black rounded px-4 py-2 hover:bg-gray-100">Previous</button>
        <span className="text-gray-600 text-sm">Page 1 of 1</span>
        <button className="border border-black rounded px-4 py-2 hover:bg-gray-100">Next</button>
      </footer>
    </div>
  );
}



